version: '3.6'
services:
  db:
    image: appsflyer-tweeter-db
    restart: always
    ports:
    - "3306:3306"
  api:
    image: appsflyer-tweeter-api
    ports:
      - "80:80"
  # consul:
  #   image: consul
  #   ports:
  #     - "1234:1234"